<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
//db_connect.inc
//Check what server you are accessing
if (strstr($_SERVER['SERVER_NAME'], 'localhost')) {
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "WP";
} else {
$servername = "talsprddb02.int.its.rmit.edu.au";
$username = "s3921946";
$password = "Rmit1234!";
$dbname = "s3921946";
}
// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
die("Connection failed: " . $conn->connect_error);
}
?>