        <header class="flexbox-item-header">
            <div class="header-container">
                <img class="img-logo" src="../images/logo.png" alt="">
                <div class="custom-select">
                    <select id="navigation-select">
                        <option value="">Select an Option:</option>
                        <option value="index.html">index</option>
                        <option value="add.html">add</option>
                        <option value="gallery.html">gallery</option>
                        <option value="pets.html">pets</option>
                    </select>
                </div>
                <div class="navigation-search">
                    <form action="/action_page.php">
                        <input type="text" placeholder="Search" name="Search">
                        <span class="material-symbols-outlined">search</span>
                    </form>
                </div>
            </div>
        </header>